Implement xenserver vbd provider list attribute
xenserver/terraform-provider-xenserver pull request #23
Opened 2024-07-02 08:21 UTC by acefei

```
$make testacc
if [ -z "/home/feis/.local/go/bin" ]; then echo "GOBIN is not set" && exit 1; fi
go mod tidy
go install .
ls -l /home/feis/.local/go/bin/terraform-provider-xenserver
-rwxrwxr-x 1 feis feis 22730403 Jul  2 16:10 /home/feis/.local/go/bin/terraform-provider-xenserver
source .env && TF_ACC=1 go test ./xenserver/ -v   -timeout 120m
=== RUN   TestAccNetworkResource
--- PASS: TestAccNetworkResource (1.82s)
=== RUN   TestAccPifDataSource
--- PASS: TestAccPifDataSource (0.76s)
=== RUN   TestAccSRDataSource
--- PASS: TestAccSRDataSource (0.77s)
=== RUN   TestAccNFSResource
--- PASS: TestAccNFSResource (9.05s)
=== RUN   TestAccSRResourceLocal
--- PASS: TestAccSRResourceLocal (3.53s)
=== RUN   TestAccSRResourceShared
--- PASS: TestAccSRResourceShared (8.30s)
=== RUN   TestAccVDIResource
--- PASS: TestAccVDIResource (3.49s)
=== RUN   TestAccVMDataSource
--- PASS: TestAccVMDataSource (2.29s)
=== RUN   TestAccVMResource
--- PASS: TestAccVMResource (3.21s)
PASS
ok      terraform-provider-xenserver/xenserver  33.232s
```

```
Terraform will perform the following actions:

  # xenserver_vm.vm will be updated in-place
  ~ resource "xenserver_vm" "vm" {
      ~ hard_drive    = [
            "0119b54e-8305-4f01-9bbc-c6e19d7f1539",
          + "96c23cce-75d7-4593-9cbd-1fdd60e0bfb0",
        ]
        id            = "edcefc7a-ca80-1218-ab43-e045cd031cb2"
        # (3 unchanged attributes hidden)
    }

Plan: 0 to add, 1 to change, 0 to destroy.

Changes to Outputs:
  ~ vm_out = {
      ~ hard_drive    = [
            "0119b54e-8305-4f01-9bbc-c6e19d7f1539",
          + "96c23cce-75d7-4593-9cbd-1fdd60e0bfb0",
        ]
        id            = "edcefc7a-ca80-1218-ab43-e045cd031cb2"
        # (3 unchanged attributes hidden)
    }
xenserver_vm.vm: Modifying... [id=edcefc7a-ca80-1218-ab43-e045cd031cb2]
xenserver_vm.vm: Modifications complete after 0s [id=edcefc7a-ca80-1218-ab43-e045cd031cb2]

Apply complete! Resources: 0 added, 1 changed, 0 destroyed.

Outputs:

vm_out = {
  "hard_drive" = tolist([
    "0119b54e-8305-4f01-9bbc-c6e19d7f1539",
    "96c23cce-75d7-4593-9cbd-1fdd60e0bfb0",
  ])
  "id" = "edcefc7a-ca80-1218-ab43-e045cd031cb2"
  "name_label" = "A test virtual-machine"
  "other_config" = tomap({})
  "template_name" = "Windows 11"
}
```

2024-07-03 05:11 UTC, xueqingz commented on xenserver/vbd_utils.go
> +		Bootable:   false,
We may need to mention somewhere, the hard drives are not allow to boot.

2024-07-03 05:13 UTC, xueqingz commented on xenserver/vbd_utils.go
> +		return "", errors.New("No available devices to attach to vm " + string(vmRef))
"unbale to find available devices"

2024-07-03 06:55 UTC, xueqingz commented on xenserver/vbd_utils.go
> +		return nil, errors.New("unable to get VDI UUIDs in plan data hard drive attributes")
what about `unable to get VDI UUIDs from "hard_drive"` ?

2024-07-03 06:59 UTC, xueqingz commented on xenserver/vbd_utils.go
> +	if vmPowerState == xenapi.VMPowerStateRunning {
For vm in different Power State, do we have test about " vm add vbd on "Halted","Paused","Suspended" state", expect there is an XAPI error for not allowed operation, but we need to try.

2024-07-03 07:00 UTC, xueqingz commented on xenserver/vbd_utils.go
> +			return nil, err
return vbdRefs, err

2024-07-03 07:00 UTC, xueqingz commented on xenserver/vbd_utils.go
> +		return "", errors.New("unable to get VDI ref, vdi UUID: " + vdiUUID)
we shouldn't return string type for xenapi.VBDRef.

return vdiRef, errors.New("unable to get VDI ref, vdi UUID: " + vdiUUID)

2024-07-03 07:03 UTC, xueqingz commented on xenserver/vbd_utils.go
> +		return "", errors.New("unable to create VBD, vdi UUID: " + vdiUUID)
same like above

2024-07-03 07:03 UTC, xueqingz commented on xenserver/vbd_utils.go
> +		return "", errors.New("unable to get VM power state, vm ref: " + string(vmRef))
return vbdRef, errors.New("unable to get VM power state")

2024-07-03 07:03 UTC, xueqingz commented on xenserver/vbd_utils.go
> +			return "", errors.New("unable to plug VBD, vdi UUID: " + vdiUUID)
same

2024-07-03 07:06 UTC, xueqingz commented on xenserver/vbd_utils.go
> +	for vdiUUID := range planVDIsMap {
what about use "slice" packages for this?

2024-07-03 07:07 UTC, xueqingz commented on xenserver/vbd_utils.go
> +				return err
if we return err here, I don't think we need "var err error"

2024-07-03 07:07 UTC, xueqingz commented on xenserver/vbd_utils.go
> +func removeVBDbyVDIUUID(session *xenapi.Session, vdiUUID string) error {
removeVBDbyVDIUUID -> removeVBDByVDIUUID

2024-07-03 07:09 UTC, xueqingz commented on xenserver/vbd_utils.go
> +			err = removeVBDbyVDIUUID(session, vdiUUID)
little confuse here.  do we need remove all vbd on this vdi or just for this VM?

2024-07-03 07:11 UTC, xueqingz commented on xenserver/vm_resouce.go
> +			"Unable to set VM from a template",
`Unable to set VM as "not a template"`

2024-07-03 07:14 UTC, xueqingz commented on xenserver/vm_resouce.go
> +	err = xenapi.VM.SetNameLabel(r.session, vmRef, plan.NameLabel.ValueString())
we'd better move all those "update" logic to vm_utils in future to make vm_resource.go very clear and clean.

2024-07-03 07:19 UTC, acefei commented on xenserver/vbd_utils.go
> +	if vmPowerState == xenapi.VMPowerStateRunning {
Just follow the logic you sent about XCM logic.

2024-07-03 07:25 UTC, acefei commented on xenserver/vm_resouce.go
> +	err = xenapi.VM.SetNameLabel(r.session, vmRef, plan.NameLabel.ValueString())
The update logic might not be necessary moved to vm_utils, considering the function is named "Update".

2024-07-03 07:48 UTC, xueqingz commented on xenserver/vm_resouce.go
> +	err = xenapi.VM.SetNameLabel(r.session, vmRef, plan.NameLabel.ValueString())
I mean, In resource update function, we do 1. check if the parameters can be updated 2. update the resources 3. get new state and store in state.  I want those steps looks clear with 3 methods if possible.

2024-07-03 08:37 UTC, acefei commented on xenserver/vbd_utils.go
> +				return err
there are many errors when I removed "var err error"

2024-07-04 08:23 UTC, acefei commented on xenserver/vbd_utils.go
> +			err = removeVBDbyVDIUUID(session, vdiUUID)
add a check if VMref matched.

2024-07-04 09:26 UTC, xueqingz commented on xenserver/vm_utils.go
>  	if err != nil {
"return err" or  "return updateVMResourceModelComputed(ctx, session, vmRecord, data)"

2024-07-04 09:28 UTC, xueqingz commented on xenserver/vbd_utils.go
> +			Default:             stringdefault.StaticString("RW"),
Do we need a filed "vbd_uuid" here?

2024-07-04 09:29 UTC, xueqingz commented on xenserver/vbd_utils.go
> +		return vbdRef, errors.New("unable to get VDI ref, vdi UUID: " + vbd.VDI.String())
expect to return Xapi error than error string.

2024-07-04 09:31 UTC, acefei commented on xenserver/vbd_utils.go
> +			Default:             stringdefault.StaticString("RW"),
what is it used for ?

2024-07-05 01:58 UTC, xueqingz commented on xenserver/vm_resource_test.go
> +					resource.TestCheckResourceAttr("xenserver_vm.test_vm", "hard_drive.#", "1"),
we can add more test cases here, eg.
"resource.TestCheckResourceAttr("xenserver_vm.test_vm", "hard_drive.0.%", "4")," 
"resource.TestCheckResourceAttr("xenserver_vm.test_vm", "hard_drive.0.mode", "RW")," 
"resource.TestCheckResourceAttr("xenserver_vm.test_vm", "hard_drive.0.bootable", "true")," 
resource.TestCheckResourceAttrSet("xenserver_vm.test_vm", "hard_drive.0.vbd_ref"),"

2024-07-05 02:16 UTC, xueqingz approved these changes

2024-07-05 02:22 UTC, xueqingz requested changes
Do we missing the change for  terraform-provider-xenserver/examples/resources/xenserver_vm/resource.tf ?

2024-07-05 03:16 UTC, xueqingz approved these changes

2024-07-05 06:30 UTC, xihuan-citrix approved these changes

2024-07-05 06:31 UTC, merged