CP-49006: ci refinement based on golang sdk publish
xenserver/terraform-provider-xenserver pull request #26
Opened 2024-07-09 03:28 UTC by initisan

2024-07-09 05:23 UTC, xueqingz approved these changes

2024-07-09 06:27 UTC, acefei requested changes

2024-07-09 06:27 UTC, acefei commented on .github/actions/setup-xenserver-sdk/extract_sdk_version.py
> +        sdk_url = f'https://github.com/xapi-project/xen-api/releases/download/v{version}/Go-SDK-prerelease-unsigned.zip'
We can just use a shell cmd to get SDK version instead of the extra py script.
![image](https://github.com/xenserver/terraform-provider-xenserver/assets/1448772/d8f4869d-7256-44ce-aeef-80a5e29c4151)

2024-07-09 07:47 UTC, initisan commented on .github/actions/setup-xenserver-sdk/extract_sdk_version.py
> +        sdk_url = f'https://github.com/xapi-project/xen-api/releases/download/v{version}/Go-SDK-prerelease-unsigned.zip'
Great.. Ya I could directly use shell here.

2024-07-10 11:03 UTC, Shiakaron approved these changes
LGTM, just a nit

2024-07-10 11:03 UTC, Shiakaron commented on .github/workflows/ci.yml
> +            grep -oE 'Software Development Kit \(SDK\) [0-9]+\.[0-9]+\.[0-9]+' | \
nit: indent this line and the one below to be more clear that it's continuation of the above line

2024-07-10 11:03 UTC, Shiakaron commented on .github/workflows/ci.yml
> +            grep -oE 'Software Development Kit \(SDK\) [0-9]+\.[0-9]+\.[0-9]+' | \
nit: indent this line and the one below to be more clear that it's continuation of the above line

2024-07-10 11:06 UTC, Shiakaron commented on .github/workflows/ci.yml
> +          url=${{ vars.XENSERVER_SDK_URL }}
Where are the variables defined? (I'm new to github workflows)

2024-07-11 02:23 UTC, initisan commented on .github/workflows/ci.yml
> +          url=${{ vars.XENSERVER_SDK_URL }}
it could be set up in the Settings -> Secrets and Variables -> Actions
![image](https://github.com/xenserver/terraform-provider-xenserver/assets/105841715/3c14c8c4-72f9-47bf-a5f8-98614f711a62)

FYI
https://docs.github.com/en/actions/learn-github-actions/variables#using-the-vars-context-to-access-configuration-variable-values

2024-07-11 02:42 UTC, acefei approved these changes

2024-07-11 05:21 UTC, merged