Private/xueqingz/CP-48977
xenserver/terraform-provider-xenserver pull request #5
Opened 2024-05-24 08:20 UTC by xueqingz

2024-05-27 02:24 UTC, acefei commented
Please add LICENSE file, as PM's requirement, we should use MIT X11 license, ref to https://en.wikipedia.org/wiki/MIT_License#X11_License

2024-05-27 02:37 UTC, acefei requested changes

2024-05-27 02:37 UTC, acefei commented on .copywrite.hcl
> +  license        = "MPL-2.0"
As PM's requirement, we need to use MIT X11 License, ref to https://en.wikipedia.org/wiki/MIT_License#X11_License
Additianally, we need to create a LICENSE file for it.

2024-05-27 03:25 UTC, acefei commented on README.md
> +Terraform allows to use local provider builds by setting a dev_overrides block in a configuration file called .terraformrc. This block overrides all other configured installation methods.
```suggestion
Terraform allows to use local provider builds by setting a dev_overrides block in a configuration file called `.terraformrc`. This block overrides all other configured installation methods.
```

2024-05-27 03:25 UTC, acefei commented on README.md
> +1. Set GOBIN to the path where Go installs binaries or use the default path:
```suggestion
1. Set `GOBIN` to the path where Go installs binaries or use the default path:
```

2024-05-27 03:25 UTC, acefei commented on README.md
> +2. Create a new file called .terraformrc in home directory (~). Change the <PATH> to the value returned from the go env GOBIN command above.
```suggestion
2. Create a new file called `.terraformrc` in home directory (~). Change the <PATH> to the value returned from the go env `GOBIN` command above.
```

2024-05-27 03:25 UTC, acefei commented on README.md
> +```shell
Please add a step to tell user to edit `main.tf` for xenserver host credentials.

2024-05-27 03:25 UTC, acefei commented on .env
> +export XENSERVER_PASSWORD="BOfpcNyZ5cMe"
Please mask the PASSWORD both here and [main.tf](examples/terraform-main).

2024-05-27 06:07 UTC, acefei commented on examples/terraform-mian/main.tf
> +
To avoid write the credentials repeatly, suggest to create a soft link for .env from repo root path, then load this environment in main.tf. 

```
+locals {
+  env_vars = { for tuple in regexall("export\\s*(\\S*)\\s*=\\s*(\\S*)\\s*", file(".env")) : tuple[0] => tuple[1] }
+}
+
 provider "xenserver" {
-  host     = "https://10.70.40.100"
-  username = "root"
-  password = "BOfpcNyZ5cMe"
+  host     = local.env_vars["XENSERVER_HOST"]
+  username = local.env_vars["XENSERVER_USERNAME"]
+  password = local.env_vars["XENSERVER_PASSWORD"]
 }
 ```

2024-05-27 06:07 UTC, acefei commented on .env
> +export XENSERVER_HOST="https://10.70.40.100"
There's no need to use double quotes for the value.

2024-05-27 07:05 UTC, acefei commented on examples/terraform-mian/main.tf
there is a typo in the path: `terraform-mian` -> `terrafrom-main`

2024-05-28 05:43 UTC, acefei submitted a review, later dismissed

2024-05-28 07:15 UTC, initisan commented on go.mod
> +require (
as I can see there are some modules (terraform plugin related) could update to latest. May worth to do that and also as a standard CI part which included in official terraform tutorial, a daily dependent bot will be run in the backend and raise PR for any module update.

Below is the latest module list I fetched today, JFYI
```go
module terraform-provider-xenserver

go 1.22.2

replace xenapi => ./goSDK

require (
	github.com/hashicorp/terraform-plugin-docs v0.19.2
	github.com/hashicorp/terraform-plugin-framework v1.8.0
	github.com/hashicorp/terraform-plugin-go v0.23.0
	github.com/hashicorp/terraform-plugin-log v0.9.0
	github.com/hashicorp/terraform-plugin-testing v1.8.0
	xenapi v0.0.0-00010101000000-000000000000
)

require (
	github.com/BurntSushi/toml v1.4.0 // indirect
	github.com/Kunde21/markdownfmt/v3 v3.1.0 // indirect
	github.com/Masterminds/goutils v1.1.1 // indirect
	github.com/Masterminds/semver/v3 v3.2.1 // indirect
	github.com/Masterminds/sprig/v3 v3.2.3 // indirect
	github.com/ProtonMail/go-crypto v1.1.0-alpha.2-proton // indirect
	github.com/agext/levenshtein v1.2.3 // indirect
	github.com/apparentlymart/go-textseg/v15 v15.0.0 // indirect
	github.com/armon/go-radix v1.0.0 // indirect
	github.com/bgentry/speakeasy v0.1.0 // indirect
	github.com/bmatcuk/doublestar/v4 v4.6.1 // indirect
	github.com/cloudflare/circl v1.3.8 // indirect
	github.com/fatih/color v1.17.0 // indirect
	github.com/golang/protobuf v1.5.4 // indirect
	github.com/google/go-cmp v0.6.0 // indirect
	github.com/google/uuid v1.6.0 // indirect
	github.com/hashicorp/cli v1.1.6 // indirect
	github.com/hashicorp/errwrap v1.1.0 // indirect
	github.com/hashicorp/go-checkpoint v0.5.0 // indirect
	github.com/hashicorp/go-cleanhttp v0.5.2 // indirect
	github.com/hashicorp/go-cty v1.4.1-0.20200414143053-d3edf31b6320 // indirect
	github.com/hashicorp/go-hclog v1.6.3 // indirect
	github.com/hashicorp/go-multierror v1.1.1 // indirect
	github.com/hashicorp/go-plugin v1.6.1 // indirect
	github.com/hashicorp/go-uuid v1.0.3 // indirect
	github.com/hashicorp/go-version v1.7.0 // indirect
	github.com/hashicorp/hc-install v0.7.0 // indirect
	github.com/hashicorp/hcl/v2 v2.20.1 // indirect
	github.com/hashicorp/logutils v1.0.0 // indirect
	github.com/hashicorp/terraform-exec v0.21.0 // indirect
	github.com/hashicorp/terraform-json v0.22.1 // indirect
	github.com/hashicorp/terraform-plugin-sdk/v2 v2.34.0 // indirect
	github.com/hashicorp/terraform-registry-address v0.2.3 // indirect
	github.com/hashicorp/terraform-svchost v0.1.1 // indirect
	github.com/hashicorp/yamux v0.1.1 // indirect
	github.com/huandu/xstrings v1.4.0 // indirect
	github.com/imdario/mergo v0.3.15 // indirect
	github.com/mattn/go-colorable v0.1.13 // indirect
	github.com/mattn/go-isatty v0.0.20 // indirect
	github.com/mattn/go-runewidth v0.0.15 // indirect
	github.com/mitchellh/copystructure v1.2.0 // indirect
	github.com/mitchellh/go-testing-interface v1.14.1 // indirect
	github.com/mitchellh/go-wordwrap v1.0.1 // indirect
	github.com/mitchellh/mapstructure v1.5.0 // indirect
	github.com/mitchellh/reflectwalk v1.0.2 // indirect
	github.com/oklog/run v1.1.0 // indirect
	github.com/posener/complete v1.2.3 // indirect
	github.com/rivo/uniseg v0.2.0 // indirect
	github.com/shopspring/decimal v1.4.0 // indirect
	github.com/spf13/cast v1.6.0 // indirect
	github.com/vmihailenco/msgpack v4.0.4+incompatible // indirect
	github.com/vmihailenco/msgpack/v5 v5.4.1 // indirect
	github.com/vmihailenco/tagparser/v2 v2.0.0 // indirect
	github.com/yuin/goldmark v1.7.1 // indirect
	github.com/yuin/goldmark-meta v1.1.0 // indirect
	github.com/zclconf/go-cty v1.14.4 // indirect
	go.abhg.dev/goldmark/frontmatter v0.2.0 // indirect
	golang.org/x/crypto v0.23.0 // indirect
	golang.org/x/exp v0.0.0-20240525044651-4c93da0ed11d // indirect
	golang.org/x/mod v0.17.0 // indirect
	golang.org/x/net v0.25.0 // indirect
	golang.org/x/sync v0.7.0 // indirect
	golang.org/x/sys v0.20.0 // indirect
	golang.org/x/text v0.15.0 // indirect
	golang.org/x/tools v0.21.0 // indirect
	google.golang.org/appengine v1.6.8 // indirect
	google.golang.org/genproto/googleapis/rpc v0.0.0-20240521202816-d264139d666e // indirect
	google.golang.org/grpc v1.64.0 // indirect
	google.golang.org/protobuf v1.34.1 // indirect
	gopkg.in/yaml.v2 v2.4.0 // indirect
	gopkg.in/yaml.v3 v3.0.1 // indirect
)

```

2024-05-28 07:23 UTC, initisan commented on main.go
> +// Copyright (c) HashiCorp, Inc.
Should it be `Copyright (c) Cloud Software Group` ?

2024-05-28 07:26 UTC, xueqingz commented on main.go
> +// Copyright (c) HashiCorp, Inc.
Yes. will update in following PR.

2024-05-28 07:35 UTC, initisan commented on xenserver/provider.go
> +func (p *Provider) Functions(_ context.Context) []func() function.Function {
Do we need to keep it here, as I can see it's not used in this version :)

2024-05-28 07:39 UTC, xueqingz commented on xenserver/provider.go
> +func (p *Provider) Functions(_ context.Context) []func() function.Function {
It's an example to show how to add functions to provider, we don't know if the functions will be used in future. I suggest we keep in code.

2024-05-28 07:40 UTC, acefei approved these changes

2024-05-28 07:40 UTC, xihuan-citrix approved these changes

2024-05-28 07:42 UTC, JinyuZhou-patty approved these changes

2024-05-28 07:47 UTC, initisan commented on README.md
> +Set up log with `github.com/hashicorp/terraform-plugin-log/tflog`. To enable logging during local develping run:
typo: developing

2024-05-28 07:49 UTC, initisan commented on xenserver/vm_resouce.go
> +// Read data from Plan, create resouce, get data from new source, set to State
typo: resource

2024-05-28 07:50 UTC, initisan commented on xenserver/vm_resouce.go
> +// Import existing resouece with id, call Read()
typo: resource. May worth to apply some typo checker in IDE :)

2024-05-28 08:05 UTC, initisan commented on examples/terraform-main/main.tf
> +  env_vars = { for tuple in regexall("export\\s*(\\S*)\\s*=\\s*(\\S*)\\s*", file("../../.env")) : tuple[0] => tuple[1] }
Besides read `.env` file directly, a more general way is to use terraform`variable` and env `TF_VAR_<variable_name>` to setup provider, as such we don't need to search path within `tf` file.

example like below
```tf
variable "xenserver_host" {
  description = "The host of the XenServer"
  type        = string
  default     = "localhost"
}

provider "xenserver" {
  host     = var.xenserver_host
}
```
within `.env` file, setup variable `TF_VAR_host username`

2024-05-28 09:04 UTC, merged